### ISSUE TITLE
ionic start IonicVueApp

### ISSUE THREAD

**Issue by testpushhydra** [ionic-team/ionic-vue-conference-app#46]
When I run the following:

ionic start IonicVueApp https://github.com/ionic-team/ionic-vue-conference-app --no-git --type=vue --cordova --no-link

Found 47 errors in 11 files.

Errors  Files
     8  src/components/Menu.vue:8
     1  src/router.ts:91
     2  src/views/About.vue:45
     1  src/views/Login.vue:26
    10  src/views/Map.vue:82
    11  src/views/SessionDetail.vue:8
     6  src/views/SessionList.vue:3
     3  src/views/SessionListFilter.vue:28
     1  src/views/SpeakerDetail.vue:66
     3  src/views/SpeakerList.vue:3
     1  src/views/Support.vue:38

Example error:

import { computed, defineComponent, getCurrentInstance, onMounted, ref, watch } from 'vue';

Cannot find module 'vue' or its corresponding type declarations.ts(2307)

**Comment by wsamoht** [comment]
You need to follow the directions under https://github.com/ionic-team/ionic-vue-conference-app?tab=readme-ov-file#getting-started.

You don't run `ionic start IonicVueApp https://github.com/ionic-team/ionic-vue-conference-app`.

**Comment by wsamoht** [comment]
Whelp, I guess I was wrong. Sorry! I see here - https://ionicframework.com/docs/cli/commands/start#examples that how you are using it is a viable option.

I ran the following and things worked.
```
ionic start "conference" https://github.com/ionic-team/ionic-vue-conference-app --no-git --cordova --no-link --type=vue
cd conference
ionic serve
```

I am running node `v20.10.0` and the latest version of the Ionic CLI which is `v7.2.0`.

**Comment by testpushhydra** [comment]
It was the node version upgrading to v20.11.0 did the trick.  Thank you for your help.
